version: '3'

services:
  richcat-dev:
    build: .
    image: richcat-dev
    container_name: richcat-dev
    ports:
      - 8000:8000 # For Sphinx
    volumes:
      - .:/home
    command: bash -c "pip install -e /home && sphinx-autobuild --host 0.0.0.0 -b html /home/doc/sphinx /home/docs"
    tty: true
