version: '3'

services:
  richcat-dev:
    build: .
    image: richcat-dev
    container_name: richcat-dev
    ports:
      - 8000:8000 # For Sphinx
    volumes:
      - type: bind
        source: "./"
        target: "/home/"
      - type: bind
        source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
    command: bash -c "pip install -e /home && make apidoc && make autobuild"
    tty: true
