name: Check version

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - id: get_version_in_branch
        name: Extract richcat version from branch name
        env:
          BRANCH_NAME: ${{github.head_ref}}
        run: |
          echo "::set-output name=version_in_branch::$(echo $BRANCH_NAME | cut -d '/' -f 2 | sed 's/v//')"

      - id: get_version_in_code
        name: Get richcat version from code
        run: echo "::set-output name=version_in_code::$(python ./scripts/get_version.py)"

      - name: Compare version
        run: |
          echo ${{ steps.get_version_in_branch.outputs.version_in_branch }} ${{ steps.get_version_in_code.outputs.version_in_code }}
