name: Dispatcher
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Dispatched
          token: ${{ secrets.GITHUB_TOKEN }}
