name: Update extension-to-alias dictionalies

on:
  push:
    branches:
      - develop

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./requirements.txt

      - name: Update
        run: |
          python ./richcat/modules/consts/_ext2alias_dic_generator.py

      - name: Push
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add ./richcat/modules/consts/_ext2alias_dic_generator.py
          git diff --exit-code --quiet ./richcat/modules/consts/_ext2alias_dic_generator.py
          if [[ $? -eq 1 ]]; then
            git commit -m "Update dictionalies";
            git push origin HEAD:${GITHUB_REF};
          fi
